apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: edutrack-api-app-tls
  namespace: default
spec:
  secretName: edutrack-api-app-tls
  renewBefore: 360h
  dnsNames:
  - edu-test-api.wetasker.com
  - www.edu-test-api.wetasker.com
  issuerRef:
    name: letsencrypt-prod-edutrack-api
    kind: ClusterIssuer